[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python telegram_bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always" 